In [129]:
import pandas as pd

In [130]:
df1 = pd.read_csv('드론실증데이터.csv')
df1 = df1.dropna()
df1

        구간     풍향    풍속    기온  운행
0   구간 1-1    0.0  0.00   0.0   0
1   구간 1-1  324.0  3.60   7.0   0
2   구간 1-1  283.0  0.90   6.0   0
3   구간 1-1  312.0  4.30  -2.0   0
4   구간 1-1  322.0  3.10   3.0   0
5   구간 1-1  345.0  3.30   0.0   0
6   구간 1-1  218.0  0.40   0.0   0
7   구간 1-1  322.0  2.80   0.0   0
8   구간 1-1  339.0  1.60   0.0   0
9   구간 1-1  191.0  0.80   0.0   0
10  구간 1-1  204.0  0.20   0.0   0
11  구간 1-1  232.0  0.50   0.2   0
12  구간 1-1  215.0  1.60   3.1   0
13  구간 1-1  211.0  0.50   0.0   0
14  구간 1-1  234.0  4.00  12.3   0
15  구간 1-1  234.0  4.00  12.3   0
16  구간 1-1  235.0  4.00  11.7   0
17  구간 1-2   15.0  0.80   0.0   0
18  구간 1-2  295.0  4.00   1.0   0
19  구간 1-2  266.0  1.50   8.0   0
20  구간 1-2  309.0  1.40  -2.0   0
23  구간 1-2  153.0  0.45  14.0   0
24  구간 1-2  233.0  0.89  14.5   0
25  구간 1-2   33.0  0.67  14.0   0
26  구간 1-2   83.0  2.30  11.0   0
27  구간 1-2  259.0  1.50   5.1   0
28  구간 1-2  193.0  3.58  14.0   0
29  구간 1-2  233.0  0.22  14.2   0

In [131]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [132]:
X = df1[['풍향','풍속','기온']]
y = df1['운행']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

model = RandomForestClassifier(n_estimators = 30, max_depth=7, random_state = 42)
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=7, n_estimators=30, random_state=42)

In [133]:
print(model.score(X_train, y_train))
print(model.score(X_test, y_test))

1.0
1.0

In [134]:
df2 = pd.read_csv('공모전_기상_데이터.csv',encoding='cp949')
#3 10 12 13
df2

,법정동,법정동코드,행정동,Year,Month,Day,Hour,season,강수,강수형태,기온,습도,풍속,풍향,바람,역풍,풍속등급,강수등급,기온등급,습도등급
0,감문면,4715035000,감문면,2016,1,1,800.0,winter,0.0,0.0,4.0,52.0,1.1,285.0,서풍,동풍,1등급,0등급,1등급,0등급
1,감문면,4715035000,감문면,2016,1,1,900.0,winter,0.0,0.0,1.5,62.0,0.7,254.0,서풍,동풍,1등급,0등급,0등급,1등급
2,감문면,4715035000,감문면,2016,1,1,1000.0,winter,0.0,0.0,0.0,69.0,0.7,315.0,북서풍,남동풍,1등급,0등급,0등급,1등급
3,감문면,4715035000,감문면,2016,1,1,1100.0,winter,0.0,0.0,0.0,73.0,0.8,300.0,북서풍,남동풍,1등급,0등급,0등급,1등급
4,감문면,4715035000,감문면,2016,1,1,1200.0,winter,0.0,0.0,0.0,76.0,0.6,321.0,북서풍,남동풍,1등급,0등급,0등급,1등급
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
798695,평화동,4715010500,평화남산동,2022,3,31,1300.0,spring,0.0,1.0,6.0,80.0,1.3,26.0,북동풍,남서풍,1등급,0등급,1등급,1등급
798696,평화동,4715010500,평화남산동,2022,3,31,1400.0,spring,0.0,0.0,4.7,89.0,0.4,305.0,북서풍,남동풍,1등급,0등급,1등급,2등급
798697,평화동,4715010500,평화남산동,2022,3,31,1500.0,spring,0.0,0.0,4.3,80.0,1.4,54.0,북동풍,남서풍,1등급,0등급,1등급,1등급
798698,평화동,4715010500,평화남산동,2022,3,31,1600.0,spring,0.0,0.0,3.7,90.0,0.3,147.0,남동풍,북서풍,1등급,0등급,1등급,2등급
798699,평화동,4715010500,평화남산동,2022,3,31,1700.0,spring,0.0,0.0,2.5,87.0,1.4,29.0,북동풍,남서풍,1등급,0등급,1등급,2등급

In [135]:
#condition = (df2.Year==2016)
df3 = df2[['풍향','풍속','기온']]
df3

           풍향   풍속   기온
0       285.0  1.1  4.0
1       254.0  0.7  1.5
2       315.0  0.7  0.0
3       300.0  0.8  0.0
4       321.0  0.6  0.0
...       ...  ...  ...
798695   26.0  1.3  6.0
798696  305.0  0.4  4.7
798697   54.0  1.4  4.3
798698  147.0  0.3  3.7
798699   29.0  1.4  2.5

[798700 rows x 3 columns]

In [136]:
model.predict(df3)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [137]:
df3['운행'] = t
df3

C:\Users\PJW\AppData\Local\Temp/ipykernel_6448/263708831.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['운행'] = t

           풍향   풍속   기온  운행
0       285.0  1.1  4.0   0
1       254.0  0.7  1.5   0
2       315.0  0.7  0.0   0
3       300.0  0.8  0.0   0
4       321.0  0.6  0.0   0
...       ...  ...  ...  ..
798695   26.0  1.3  6.0   0
798696  305.0  0.4  4.7   0
798697   54.0  1.4  4.3   0
798698  147.0  0.3  3.7   0
798699   29.0  1.4  2.5   0

[798700 rows x 4 columns]

In [138]:
df3['운행'].unique()

array([0], dtype=int64)