In [1]:
!pip install haversine
import pandas as pd
from haversine import haversine

Requirement already satisfied: haversine in c:\users\pjw\anaconda3\lib\site-packages (2.5.1)

In [2]:
#위도 경도로 거리 계산하기 (km)
#김천시청->등곡지 주차장 [구간1-1]
haversine([36.139771399999596,128.10523559999965],[36.1676022000002,128.1143620999994])
#등곡지 주차장 -> 어모면사무소 [구간1-2]
haversine([36.1676022000002,128.1143620999994],[36.180678,128.118928])

1.5106212976410898

In [3]:
df1 = pd.read_csv('드론실증데이터.csv')
df1 = df1.dropna()
df1

        구간     풍향    풍속    기온  운행  비행시간(분)        거리
0   구간 1-1    0.0  0.00   0.0   0       12  3.201292
1   구간 1-1  324.0  3.60   7.0   0       11  3.201292
2   구간 1-1  283.0  0.90   6.0   0       11  3.201292
3   구간 1-1  312.0  4.30  -2.0   0       12  3.201292
4   구간 1-1  322.0  3.10   3.0   0       11  3.201292
5   구간 1-1  345.0  3.30   0.0   0       13  3.201292
6   구간 1-1  218.0  0.40   0.0   0       12  3.201292
7   구간 1-1  322.0  2.80   0.0   0       12  3.201292
8   구간 1-1  339.0  1.60   0.0   0       12  3.201292
9   구간 1-1  191.0  0.80   0.0   0       12  3.201292
10  구간 1-1  204.0  0.20   0.0   0       12  3.201292
11  구간 1-1  232.0  0.50   0.2   0       11  3.201292
12  구간 1-1  215.0  1.60   3.1   0       12  3.201292
13  구간 1-1  211.0  0.50   0.0   0       12  3.201292
14  구간 1-1  234.0  4.00  12.3   0       11  3.201292
15  구간 1-1  234.0  4.00  12.3   0       12  3.201292
16  구간 1-1  235.0  4.00  11.7   0       11  3.201292
17  구간 1-2   15.0  0.80   0.0   0        9  1.510621
18  구간 1-2  295.0  4.00   1.0   0       10  1.510621
19  구간 1-2  266.0  1.50   8.0   0       11  1.510621
20  구간 1-2  309.0  1.40  -2.0   0       10  1.510621
23  구간 1-2  153.0  0.45  14.0   0       11  1.510621
24  구간 1-2  233.0  0.89  14.5   0       10  1.510621
25  구간 1-2   33.0  0.67  14.0   0       10  1.510621
26  구간 1-2   83.0  2.30  11.0   0       14  1.510621
27  구간 1-2  259.0  1.50   5.1   0       11  1.510621
28  구간 1-2  193.0  3.58  14.0   0       11  1.510621
29  구간 1-2  233.0  0.22  14.2   0       11  1.510621

In [12]:
df2 = pd.read_csv('공모전_기상_데이터.csv', encoding='cp949')
condition = (df2['Year']==2022)&(df2['행정동']=='감문면')|(df2['행정동']=='감천면')|(df2['행정동']=='개령면')|(df2['행정동']=='구성면')|(df2['행정동']=='남면')|(df2['행정동']=='농소면')|(df2['행정동']=='어모면')
df2 = df2[condition]
df2=df2[['행정동','풍향','풍속','기온']]
df2

        행정동     풍향   풍속   기온
21920   감문면  188.0  0.2  0.0
21921   감문면  310.0  0.1  0.0
21922   감문면  135.0  0.1  0.0
21923   감문면  112.0  0.3  0.0
21924   감문면  109.0  0.0  0.0
...     ...    ...  ...  ...
524855  어모면   69.0  3.4  4.9
524856  어모면   37.0  3.0  4.5
524857  어모면   54.0  1.4  4.3
524858  어모면   51.0  1.1  3.2
524859  어모면   29.0  1.4  2.5

[137820 rows x 4 columns]

In [5]:
from sklearn.linear_model import LinearRegression
from matplotlib import pyplot as plt
import numpy as np

In [111]:
from sklearn.model_selection import train_test_split
df1 = pd.read_csv('드론실증데이터_전처리.csv')
X = df1[['풍향','풍속','기온','거리']]
y = df1['비행시간(분)']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7,test_size=0.3)

In [110]:
#예시) 선형회귀분석 모델
m = LinearRegression()
m.fit(X_train,y_train)
pred = m.predict(X_test)

print("예측값:",pred)
print("정확도:",m.score(X_train,y_train))

예측값: [11.66641298 10.39467373 10.55060049 11.51495959 11.72644453 10.55035159
 10.17285298 10.10020162 11.64975673]
정확도: 0.5435431466556404

In [14]:
#실제 데이터로 예측해보기
#testdata 만들기(공모전 기상 데이터 활용 )
testdf = pd.DataFrame({'풍향':[321,230,245,354,91],
                     '풍속':[0.5,0.9,2.5,1,1.1],
                     '기온':[0,23.7,12.2,21.3,0],
                     '거리':[7.91729582428519,11.342248543572,6.44385088324697,16.1733180111404,7.91729582428519]})
testdf

    풍향   풍속    기온         거리
0  321  0.5   0.0   7.917296
1  230  0.9  23.7  11.342249
2  245  2.5  12.2   6.443851
3  354  1.0  21.3  16.173318
4   91  1.1   0.0   7.917296

In [112]:
pred_test = m.predict(testdf)

print(pred_test)

[15.32752782 17.65836016 13.95034068 21.37606212 14.88559067]

In [37]:
#예시2) 랜덤포레스트 모델
from sklearn.ensemble import RandomForestRegressor 
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X = df1[['풍향','풍속','기온','거리']]
y = df1['비행시간(분)']
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.1)
X_test

       풍향   풍속    기온        거리
26   83.0  2.3  11.0  1.510621
4   322.0  3.1   3.0  3.201292
6   218.0  0.4   0.0  3.201292

In [38]:
model = RandomForestClassifier(n_estimators = 30, max_depth=7, random_state = 42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(y_pred)
print(accuracy_score(y_test, y_pred))

[11 11 12]
0.6666666666666666

In [17]:
#실제 데이터로 예측해보기
testdf = pd.DataFrame({'풍향':[321,230,245,354,91],
                     '풍속':[0.5,0.9,2.5,1,1.1],
                     '기온':[0,23.7,12.2,21.3,0],
                     '거리':[7.91729582428519,11.342248543572,6.44385088324697,16.1733180111404,7.91729582428519]})
testdf

    풍향   풍속    기온         거리
0  321  0.5   0.0   7.917296
1  230  0.9  23.7  11.342249
2  245  2.5  12.2   6.443851
3  354  1.0  21.3  16.173318
4   91  1.1   0.0   7.917296

In [21]:
test = model.predict(testdf)
test

array([12, 11, 11, 11, 12], dtype=int64)